name : AndroidBuild
on:
   pull_request:
     branches:[ main ]
   push:
     branches:[ main ]

jobs:
  build:
    runs-on : mac
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0

      - name: Build with Gradle
        uses: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/uplaod-artifact@v3.1.3
        with: News App
        path: app/build/outputs/apk/app-debug.apk